language: node_js
node_js:
  - "6"

env:
  matrix:
    secure: f+vkkM3Pmg68KJpGRYvb+Z7czBT/9++GUud5ihBnCy6RQWju94d8KRpyaVQgCyeeKGrH9ni23B6mE02lIZNBLWDM16oclOaS0+begtaenrPhFr0wdJ6ZBVnT6rXNmDZD5wbLXxOZojukjSPTgvYu/2YxqLAbnr785eQCZvn5RyXCmQt8rgeRMnaEO/1ESd/37WrE8Uhvxq/+FH38CirYRaSqC8L/HkPB5kN5PPOq3GNkd6wkCwmoh8zgQSfRJJThqXfHUFYCCGp6gC9irAUFCwVLDpZsOn44jxlSNFXiuuM2LZKptujKSmSzZV40kjqPR+18gXgmwKATNcqtIB8z8Mm/5vmc7dhQcTfmewgNT9VfQBU1f0B4NwleTV8cjERweznLGa0Ke5/jOj9ju5Ckq7i27kTAb6ZFaEuUdZbn+Y/X58eH0t91s/x6ztqnNRT7wFC6X8cI3N2dJxAddWrL9jDvv+vwcfigYw/Bu671yO/7bdEOsQRNOx/HUbjJZTzYzhu1MB1idNDUTEycVQO6wv6zqf23hVH8O4TII3EGAF6HHUxuh6qiR8ZzjROYaJg8nibcHreengY1pm+tfiX3o6gwI/DMkEdQaklbMPQ6p0hVmKXLeK68Ym17nOd7T1uxWC3FKfVFcOQzChjD0sEcp/mD62Su3fcMpnUL6yyO338=

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install p7zip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y p7zip-full; fi

install:
  - npm install
  - npm install -g electron-packager

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run macbuild; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run linuxbuild; fi

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 7z a -tzip -mx9 BloodHound-darwin-x64-$TRAVIS_COMMIT.zip BloodHound-darwin-x64 > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 7z a -tzip -mx9 BloodHound-linux-ia32-$TRAVIS_COMMIT.zip BloodHound-linux-ia32 > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 7z a -tzip -mx9 BloodHound-linux-x64-$TRAVIS_COMMIT.zip BloodHound-linux-x64 > /dev/null; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 7z a -tzip -mx9 BloodHound-linux-armv7l-$TRAVIS_COMMIT.zip BloodHound-linux-armv7l > /dev/null; fi

deploy:
  provider: script
  script: /bin/bash deploy.sh
  skip_cleanup: true
  on:
    branch: master

notifications:
  email: false

branches:
  only:
    - master
